### ISSUE TITLE
Portal user is able to login in LMS , with his email id.

### ISSUE THREAD

**Issue by tejasbizacuity** [ServAcuity/ServAcuity#196]
![Image](https://github.com/user-attachments/assets/bdb71c72-5d7a-4b61-a307-b79d4a45751b)

**Comment by siddharthnair31** [comment]
This is bound to happen because we are using the same cognito userpool for both lms and portal so the users are same it will be resolved if we create a new userpool for lms not an issue in dev in uat and prod we will have separate cognito userpool.
@leelakrishna-t you can close this ticket from your end.

**Comment by leelakrishna-t** [comment]
This ticket is closed as per the comments from Sid.
